jsuites/jsuites

dist/jsuites.js

This fixes #39 and also related https://github.com/paulhodel/jexcel/issues/1031.

Fix date to string conversion

---

dist/jsuites.css
dist/jsuites.js

With this PR, you can insert submenu to contextmenu. And submenu to submenu etc.
In options of contextmenu add properties submenu who including list of items
code for test
```HTML
<script>
var contextMenu = jSuites.contextmenu(document.getElementById('contextmenu'), {
items:[
{
title:'Copy',
shortcut:'Ctrl + C',
onclick:function() {
alert('Copy');
}
},
{
type:'line'
},
{
title:'Visit the website',
onclick:function() {
window.open('https://bossanova.uk/jexcel/v3/examples');
}
},
{
title:'Google',
disabled: true,
onclick:function() {
alert('jSuites v2')
}
},
{
title: 'Sub context menu',
submenu: [
{
title:'Sub menu 1',
shortcut:'Ctrl + X',
onclick:function() {
alert('SubMenu 1-1');
}
},
{
title:'Sub menu 2',
disabled: true,
onclick:function() {
alert('SubMenu 1-2')
}
},
{
title: 'Sub sub …
```

Add feature submenu on contextmenu

---

dist/jsuites.js

When form auto generate with textarea and you would make rich editor on textarea, i have creating a patch for integrate that

Add compatibility textarea for editor

---

src/mask.js

Fixing decimal splitting that ignore `decimal` configuration.

Fixing decimal splitting

---

src/color.css
src/color.js

Create button reset for JExcel can reset color cell and for same palette easy on app, can defined palette on` jSuites.palette` like
```
jSuites.palette = [
[
"rgb(0, 0, 0)",
"rgb(67, 67, 67)",
"rgb(102, 102, 102)",
"rgb(153, 153, 153)",
"rgb(183, 183, 183)",
"rgb(204, 204, 204)",
"rgb(217, 217, 217)",
"rgb(239, 239, 239)",
"rgb(243, 243, 243)",
"rgb(255, 255, 255)"
],
[
"rgb(152, 0, 0)",
"rgb(255, 0, 0)",
"rgb(255, 153, 0)",
"rgb(255, 255, 0)",
"rgb(0, 255, 0)",
"rgb(0, 255, 255)",
"rgb(74, 134, 232)",
"rgb(0, 0, 255)",
"rgb(153, 0, 255)",
"rgb(255, 0, 255)"
],
[
"rgb(230, 184, 175)",
"rgb(244, 204, 204)",
"rgb(252, 229, 205)",
"rgb(255, 242, 204)",
"rgb(217, 234, 211)",
"rgb(208, 224, 227)",
"rgb(201, 218, 248)",
"rgb(207, 226, 243)",
"rgb(217, 210, 233)",
"rgb(234, 209, 220)"
],
[ …
```

JColor : Create button reset (disable by default) + Globale palette color

---

src/color.js

Fix for delete <script> tag insered to end of my file 😊

Fix tag <script> insered to end

---

dist/jsuites.css
dist/jsuites.js
src/calendar.js
src/org.css
src/org.js

changes in validRange property and highlight, its working as well.

Fix: jcalendar validRange and highlight fixed

---

src/progress.css
src/progress.js

Progress modal with progressbar
system async implemented for big script

Plugin progress modal

---

src/dropdown.js

Sort data before set data on dropdown
options: sortResults
if false : no sort
if true : default sort
if function : custom sort

sort data on dropdown

---

src/dropdown.js

When you use autocomplete, if user use quickly this dropdown "1 letter + Enter" for make a quick select if autofocus = true, or quick filter

Quick select

---

src/dropdown.js

Option for auto select first result on list after "find"

Add autofocus option

---

src/animation.css

Add animation spin

---

src/layout.css

Add management medium screen (tablet)

Add hide/show for tablet screen

---

src/dropdown.js

Fix sort dropdown for number

---

src/dropdown.css
src/dropdown.js

Add disabled option present on prod but not in src
Maybe check on css if all is ok

Dropdown : Add disabled options

---

src/dropdown.js

To modify Item before insert (Text or custom Id)

Dropdown : add onbeforeinsert

---

src/dropdown.js

Fix on insert argument : Third : newItem after created item

Dropdown : Fix oninsert argument

---

src/dropdown.js

dropdown improvements to auto-select if only option and handle tab, page up and page down.

dropdown improvements: auto-select if only option, handle more keys

---

src/dropdown.js

Update add function for :
- Add new item with title and Id defined before
- Add open custom form Add for new Item (For example usage : open form for create new user with all fields, and after return on dropdown only title + id)

Dropdown : Update add function

---

src/search.js

List of Fix : 
- Add events keyup & keydown on `obj.options.input`
- Test compare : Text str is transform to lowerCase

Some fix for search.js

---

dist/jsuites.js

Improve setDictionary to give possibility set dictionary many time without replace previsous dictionary but add new items in dictionary

Improve setDictionary

---

src/contextmenu.css
src/contextmenu.js

Improve contextmenu for mobile.
Add header with title et button close
Add icon

Improve contextmenu for mobile.

---

dist/jsuites.js

Manage when object use getter and setter (the function hasOwnProperty doesn't work in this case)

Improve path

---

src/picker.css

When you have more 5 items in jpicker, make a overflow and when you have large picker, use all width available

Add CSS for jpicker

---

src/modal.js

add call close when you use escape key

Modal : add call close when you use escape key
